### ISSUE TITLE
Fix pluralization in i18n in admin notices

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/BuddyPress-Registration-Options#108]
```
$s = '';
if ( $member_requests > 1 ) {
	$s = 's';
}
$message = '<div class="error"><p>';
$message .= sprintf(
	__( 'You have %s new member request%s that need to be approved or denied. Please %s to take action', 'bp-registration-options' ),
	sprintf(
		'<a href="%s"><strong>%s</strong></a>',
		admin_url( '/admin.php?page=bp_registration_options_member_requests' ),
		$member_requests
	),
	$s,
	sprintf(
		'<a href="%s">%s</a>',
		admin_url( '/admin.php?page=bp_registration_options_member_requests' ),
		__( 'click here', 'bp-registration-options' )
	)
);
$message .= '</p></div>';
```
Better ways to handle that "S" on plural requests.

**Comment by tw2113** [comment]
Fixed in 4.3.0 branch

**Comment by christianwach** [comment]
@tw2113 Unfortunately, this won't localise plurals properly in many languages. I'd go with something more like:

```php
$message .= sprintf(
	_n(
		'You have %d new member request that needs to be approved or denied. ', // singular
		'You have %d new member requests that need to be approved or denied. ', // plural
		$member_requests, // number
		'bp-registration-options' // domain
	),
	$member_requests // substitution
);

$message .= sprintf( 
	__( 'Please <a href="%s">click here</a> to take action.', 'bp-registration-options' ), 
	admin_url( '/admin.php?page=bp_registration_options_member_requests' )
);
```

Admittedly you'd lose the number being a link, but you'd gain proper localisation.

**Comment by tw2113** [comment]
I'll look things over a little bit more with this one, but I am trying to avoid html in the gettext strings.

**Comment by christianwach** [comment]
Perhaps make the whole string a button-style link?

```php
$call_to_action = '<a href="' . admin_url( '/admin.php?page=bp_registration_options_member_requests' ) . '" class="button button-small">' . __( 'Take action', 'bp-registration-options' ) . '</a>';
```

This uses built-in WP styles so should be recognisable to most users. You could use other built-in styles if you want to make it more prominent, but that'd be my preference.

**Comment by tw2113** [comment]
Pushed up my latest version. Let me know if you see any issues with it as is.

**Comment by christianwach** [comment]
Do you mean starting [here](https://github.com/WebDevStudios/BuddyPress-Registration-Options/blob/4.3.0/includes/admin.php#L294)? If so, you can remove lines 294-297 which are redundant. Also, I think you meant to write:

```php
$message .= sprintf(
	_n(
		'You have %d new member request that needs to be approved or denied.',
		'You have %d new member requests that needs to be approved or denied.',
		$member_requests,
		'bp-registration-options'
	),
	$numeral_url
);
```

Other than that, looks okay to me.

**Comment by tw2113** [comment]
Michael, remove https://github.com/WebDevStudios/BuddyPress-Registration-Options/blob/4.3.0/includes/admin.php#L300:L304

**Comment by tw2113** [comment]
Removed that snippet in 4.3.0 branch.
