### ISSUE TITLE
Buddypress

### ISSUE THREAD

**Issue by prerna273** [WebDevStudios/BuddyPress-Registration-Options#148]
Can any one help me to  i have three user category in buddy press registration form and want to assign each category user a different roll on signup and want to redirect them to their category page after login...is that possible ????e help....any help will be appreciated...

Thanks in advance...!!!
 i tried this code but don't know what is the meaning of Ich bin in fifth row.....
add_action('bp_core_activated_user', 'bp_custom_registration_role',10 , 3);
function bp_custom_registration_role($user_id, $key, $user) {
   $userdata = array();
   $userdata['ID'] = $user_id;
   $userdata['role'] = xprofile_get_field_data('Ich bin', $user_id);
   
   if ($userdata['role'] == 'Dienstleister') {
        $userdata['role'] = 'dienstleister';
   }
   elseif ($userdata['role'] == 'Kunde') {
        $userdata['role'] = 'kunde';
   }
   //only allow if user role is my_role
   if (($userdata['role'] == "dienstleister") or ($userdata['role'] == "kunde")) {
        wp_update_user($userdata);
   }
  }

**Comment by tw2113** [comment]
Hi @prerna273,

The current version of the plugin doesn't interject or alter the signup form at all. That's all BuddyPress core creating the form. We do our thing after the user creation process has been done within WordPress core.

Tha said, "Ich bin" looks to be the name of an XProfile field that is either from BuddyPress core or a custom user-created one.

Closing as a non issue, but that doesn't disable ability to comment after the fact.
