### ISSUE TITLE
Error: an empty page that only shows: -2

### ISSUE THREAD

**Issue by islamrashad2001** [WebDevStudios/BuddyPress-Registration-Options#177]
Hello, 
I am trying to approve some requests to join the BP forum on my site. Whenever I try, it's giving me an empty page that only shows: -2
Can anyone help, please? 
Thanks

**Comment by tw2113** [comment]
What are you clicking on/doing right before this `-2` appears, because it sounds like possibly an error/issue coming from somewhere else. We don't have anything set up to do that ourselves.

**Comment by islamrashad2001** [comment]
Hi,
Thanks a lot for your reply.
I check the box before every member name and just click on approve.
Islam



Islam Karkour, Ph.D.
Lecturer of Arabic
Department of Languages, Literatures, and Cultures
University of New Hampshire
G14 Murkland Hall
15 Library Way
Durham, NH 03824

(He/Him/His)


________________________________

**Comment by tw2113** [comment]
Are you able to try things with all other plugins disabled?
