### ISSUE TITLE
Buddy Press registration email error

### ISSUE THREAD

**Issue by Klau54** [WebDevStudios/BuddyPress-Registration-Options#182]
So I was testing out the Buddy press registration plugin that works with Buddy forms. When I tested out the dummy accounts , As an admin I could see in the member request who is requesting to become a subscriber to the website. When I clicked approve, there should have been an email sent to the dummy account's email address. Problem is that there is no email of approval showing up on the dummy account's email inbox. What could be causing this issue?

**Comment by tw2113** [comment]
What "Buddy forms" are you referring to, in case it's playing a part in things?

**Comment by Klau54** [comment]
By “buddy form” I mean the plugin called Buddy forms created by theme craft. To be more exact I have three “Buddy”
Plugins working together. There is Buddy Press Registrations, Buddy Press members only, and then there’s Buddy Forms. I’m more concerned with Buddy Press registration since it is the plugin responsible for sending and email of approval to users who want to become members.

**Comment by Klau54** [comment]
Buddy Press as a whole is working properly when it comes to emails, even the test emails written in Latin won't show up in my inbox. The major concern for me is that activation emails are being sent to users who are approved.

**Comment by tw2113** [comment]
Out of curiosity, has anyone checked spam filters just in case?

Beyond that, we don't do anything special outside of passing things through `wp_mail()` and some filters to get html support for the emails so it's a bit hard for me to point to anything specific and go "it's in this area!"

**Comment by Klau54** [comment]
Yeah, I’ve check the dummy account’s spam folder and there is nothing there.

**Comment by Klau54** [comment]
I've tried using SMTP but even then the email approving the user is not going to the inbox or my junk email. What should I do from here?

**Comment by tw2113** [comment]
Dunno what to tell you without having much more elevated access to the install to see where it's possibly failing for sure.

I'm looking at our code, specifically inc/admin.php and the `bp_registration_options_form_actions()` function where we process approval/denial.

The only spots I see that would probably stop things would be the `check_admin_referer( 'bp_reg_options_check' );` result, and then if the `$send` variable never gets set to true, which it should if "deny" or "approve" are the performed actions. Those values would come from a `$_POST['moderate']` being set. Below are some links to the specific spots in the code where we handle these parts mentioned.

Function declaration: https://github.com/WebDevStudios/BuddyPress-Registration-Options/blob/master/includes/admin.php#L160

Moderate $_POST value checks: https://github.com/WebDevStudios/BuddyPress-Registration-Options/blob/master/includes/admin.php#L193-L221

Section where we check if we should send anything, for a given approved user: https://github.com/WebDevStudios/BuddyPress-Registration-Options/blob/master/includes/admin.php#L289-L315

I wonder if a plugin like https://wordpress.org/plugins/email-log/ could help deduce what's going on and why.

**Comment by Klau54** [comment]
I resolved the issue everything is running smoothly again thank you for time.

**Comment by tw2113** [comment]
What was the issue, out of curiosity in case someone else comes in with the same issue?

**Comment by Klau54** [comment]
So for background information, I have a friend who was working on an app which works along side with some of the plugins. He did some work on a tools app for the site. Whatever he did he resolved the Buddy Forms issue along with a couple of other ones. I can’t give you an exact detail. Bur from what he said it had something to do with cookie parsing.

**Comment by tw2113** [comment]
Gotcha. Thanks for providing what you could :)

Glad to hear things are working again.
