### ISSUE TITLE
BP 1.9 notifications

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/BuddyPress-Registration-Options#46]
How can we leverage this for admins? :D

**Comment by tw2113** [comment]
https://codex.buddypress.org/developer/function-examples/bp_notifications_add_notification/

https://bbpress.trac.wordpress.org/browser/tags/2.5.3/includes/extend/buddypress/notifications.php

**Comment by tw2113** [comment]
Option to choose between email or BP notification?

**Comment by tw2113** [comment]
Added initial support for notifications of new users in 4.3.0 branch. Gonna disregard email vs notification for the moment.

**Comment by tw2113** [comment]
See #107 for extra additions including notifying ALL admin users instead of just one.

**Comment by tw2113** [comment]
Give props to appropriate person

**Comment by modemlooper** [comment]
https://webdevstudios.com/2015/10/06/buddypress-adding-custom-notifications/

**Comment by tw2113** [comment]
Will look over that post as well to merge all the best ideas

**Comment by colabsadmin** [comment]
Yes, give props to @modemlooper since it was his initial code that I tweaked.  :)

**Comment by tw2113** [comment]
Modified to notify all users and fixed i18n spot and changed component name to match our plugin name.
