### ISSUE TITLE
Plugin does not work if Buddypress is installed else than blog_id 1

### ISSUE THREAD

**Issue by idea--list** [WebDevStudios/BuddyPress-Registration-Options#70]
First of all i really love the idea of this plugin, but it just does not work in my setup.

I have a WP3.9.1 multisite with WP Multi Network plugin activated. Network 1 has site A which is open for the public and has no Buddypress at all. Network 2 has site B that is a closed social site for a small group of people with BP installed and on this site i would need the user approval function of this plugin.

For some reason it does not get the job done.

**Comment by tw2113** [comment]
Removed this limit in the 4.3.0 branch, but will be further testing in multisite cases.

Closing in the meantime.
