### ISSUE TITLE
Hook into initial registration notification email instead of sending our own.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/BuddyPress-Registration-Options#78]
Is there hooks available for the new user registration notification for WP admins that we could append to instead of create our own.

**Comment by modemlooper** [comment]
do_action( 'bp_core_activated_user'

**Comment by tw2113** [comment]
For multisite:
newblog_notify_siteadmin

Filters the message used in the email.

**Comment by tw2113** [comment]
Gonna axe this one, I'd really not prefer dealing with pluggable functions, and I'm sure some of the BP core devs would hug me for that as well.
