### ISSUE TITLE
Conflict with W3 Total Cache plugin's Database Caching

### ISSUE THREAD

**Issue by tunjic** [WebDevStudios/BuddyPress-Registration-Options#79]
The conflict creates double entries in the Members Requests Queue.

Workaround is to add "bprwg" (no quotes) to the "Ignored query stems” list in the w3 total cache “database caching” setting page.

**Comment by tw2113** [comment]
Curious if there's a hook for that option/setting that we can auto-add ourselves to.

**Comment by tw2113** [comment]
Not really seeing a way to filter this in, by any means. May be stuck with just a FAQ for the topic, and even then I haven't seen it come up very frequently, if at all.
