### ISSUE TITLE
Update plugin to not rely on $_GET['key'] for activation message display.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/BuddyPress-Registration-Options#82]
BP 2.2 had changes regarding the activation key url, and it's momentarily breaking our plugin message display.

https://wordpress.org/support/topic/activate-alert-message-not-being-injected-w-buddypress-22?replies=7#post-6530040

**Comment by colabsadmin** [comment]
Any ETA on this?  Its stopping us from updating BP.

**Comment by tw2113** [comment]
This is only affecting the display of a message on one location, it shouldn't be affecting the prevention of access anywhere, last I checked.

**Comment by tw2113** [comment]
Fixed in bdb79c8
