### ISSUE TITLE
AJAX-reloaded tab content are losing applied filters.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/BuddyPress-Registration-Options#84]
This is allowing moderated users to regain UI elements that are normally hidden.

**Comment by tw2113** [comment]
Should be able to pass in noajax classes to prevent.

May not be able to do that via dev tools and source tab, so need to have them in from the getgo.

**Comment by tw2113** [comment]
Not a lot going on for filters to handle this from the start, 4.2.6 has an attempt to use js to add the class. It's far from perfect.

**Comment by christianwach** [comment]
Hmm, I see what you mean. I've been looking at this and it's not obvious where to hook in to override the default behaviour. I'll keep looking...

**Comment by tw2113** [comment]
I'm curious if the 2.3 release of BuddyPress may have helped somehow, but I'm not super hopeful.

**Comment by christianwach** [comment]
All AJAXy stuff goes through `bp_legacy_theme_object_template_loader()`, but that function has no action that can be hooked into. However, it *is* possible to hook into the WordPress action that triggers the call to that function. So, replace [line 192 of core.php](https://github.com/WebDevStudios/BuddyPress-Registration-Options/blob/master/includes/core.php#L192) with:

```php
// check for routing via AJAX
if ( defined( 'DOING_AJAX' ) AND DOING_AJAX ) {

	// test for BP object
	if ( ! empty( $_POST['object'] ) ) {

		// sanitise it
		$object = sanitize_title( $_POST['object'] );

		// filter before BP
		add_filter( 'wp_ajax_' . $object . '_filter', 'bp_registration_hide_ui', 1 );

	}

} else {
	add_action( 'bp_ready', 'bp_registration_hide_ui' );
}
```

It's not pretty, but it seems to work :-)

I'll create a PR instead if that's easier for you to review.

**Comment by tw2113** [comment]
a PR would be appreciated.

**Comment by christianwach** [comment]
gotcha... on its way

**Comment by christianwach** [comment]
Oh dammit, it fails on the sitewide activity stream. But it does work on the groups and members directories. It's a start...

**Comment by christianwach** [comment]
Okay, second commit seems to solve this - sitewide activity AJAX updates seem to come via 'init', so `bp_registration_hide_ui()` can be called directly when there's no `$object`. It seems ;-) Testing needed, methinks. Gotta run now.

**Comment by tw2113** [comment]
Shall try to give it some tire kicking soon. I appreciate the help.

**Comment by christianwach** [comment]
HTH. I think the code probably needs something like `if ( ! bp_is_active( $object ) ) return;` before adding the filter. And it feels a bit hacky. I'd request a `do_action()` in `bp_legacy_theme_object_template_loader()` if I were you.

**Comment by tw2113** [comment]
Bare minimum, it gives me a lead on things.

**Comment by tw2113** [comment]
https://github.com/WebDevStudios/BuddyPress-Registration-Options/commit/71314a3e31a03e0f78cd8346f13645582c868b32

**Comment by tw2113** [comment]
Gonna leave the issue open a bit longer for the sake of reminding to keep testing.

**Comment by tw2113** [comment]
/* hiding moderated users (and admins) on the members listing */
function bpdev_exclude_users($qs=false,$object=false){
	// Admins
	$excluded_user='1,4'; 

	// Moderated users
	$pending_users = bp_registration_get_pending_users();
	foreach( $pending_users as $pending_user ) {
		$pending_user = $pending_user->user_id;
		$excluded_user .= ',';
		$excluded_user .= $pending_user;
	}

    if($object != 'members') //hiding from members
    return $qs;

    $args=wp_parse_args($qs);

    //except for friends

    if(!empty($args['user_id']))
    return $qs;	

    if(!empty($args['exclude']))
    $args['exclude'] = $args['exclude'].','.$excluded_user;
    else
    $args['exclude'] = $excluded_user;

    $qs = build_query($args);

    return $qs;

}
add_action('bp_ajax_querystring','bpdev_exclude_users',20,2);
