### ISSUE TITLE
WP Better Emails -- won't customize the notification email

### ISSUE THREAD

**Issue by webxolutions** [WebDevStudios/BuddyPress-Registration-Options#96]
Greetings!

I'm using your fabulous plugin, which works great. The only issue I've come across so far is that the emails will not get customized with the WP Better Emails plugin, which basically creates a nice looking email message. Instead, the message is the default plain message. I haven't figured out how to get the WPBE plugin to hook before sending out the email. It will customize any other message that gets emailed from the website, though...

Has anyone else encountered this issue? Can you provide some hints to get this second plugin to customize the email before sending out? One attempt was to use Plugin Organizer, but that won't work either.

Any and all help will be appreciated!

**Comment by tw2113** [comment]
Best I can say is that we use the standard wp_mail() function that comes with WordPress itself. Not sure if we're somehow hooking in and firing before WP Better Emails can get to it or not, as I'm not familiar with that plugin.

**Comment by webxolutions** [comment]
Okay, thanks. I'll keep investigating. Thanks for the quick response!
